# Generated by Django 5.1.2 on 2024-10-22 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BillAPI', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='recurring',
            field=models.BooleanField(),
        ),
    ]
